-- Phase 0: Create the Snowflake database, schema, and warehouse.
-- Usage:
--   snowsql -c assessment -f snowflake/00_bootstrap.sql

CREATE WAREHOUSE IF NOT EXISTS WH_XS
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PLANNING_DB;
USE DATABASE PLANNING_DB;

CREATE SCHEMA IF NOT EXISTS PLANNING;
USE SCHEMA PLANNING;

SHOW WAREHOUSES LIKE 'WH_XS';
SHOW DATABASES LIKE 'PLANNING_DB';
SHOW SCHEMAS LIKE 'PLANNING';
